[target]
programs=testhash
[require]
packages=indy
packagedir=../../

[compiler]
unittargetdir=units/$(CPU_TARGET)-$(OS_TARGET)
#For some reason, we can't use "unitdir" here.  It causes some strange bugs.
#This is a workaround.
options=-dUseCThreads -gl

[install]
fpcpackage=y