brcc32 RADStudio_2009\IndySystem.rc
brcc32 RADStudio_2009\IndyCore.rc
brcc32 RADStudio_2009\IndyProtocols.rc
brcc32 RADStudio_2009\dclIndyCore.rc
brcc32 RADStudio_2009\dclIndyProtocols.rc
brcc32 RADStudio_2010\IndySystem.rc
brcc32 RADStudio_2010\IndyCore.rc
brcc32 RADStudio_2010\IndyProtocols.rc
brcc32 RADStudio_2010\dclIndyCore.rc
brcc32 RADStudio_2010\dclIndyProtocols.rc
brcc32 RADStudio_XE\IndySystem.rc
brcc32 RADStudio_XE\IndyCore.rc
brcc32 RADStudio_XE\IndyProtocols.rc
brcc32 RADStudio_XE\dclIndyCore.rc
brcc32 RADStudio_XE\dclIndyProtocols.rc
brcc32 RADStudio_XE2\IndySystem.rc
brcc32 RADStudio_XE2\IndyCore.rc
brcc32 RADStudio_XE2\IndyProtocols.rc
brcc32 RADStudio_XE2\dclIndyCore.rc
brcc32 RADStudio_XE2\dclIndyProtocols.rc
brcc32 RADStudio_XE3\IndySystem.rc
brcc32 RADStudio_XE3\IndyCore.rc
brcc32 RADStudio_XE3\IndyProtocols.rc
brcc32 RADStudio_XE3\dclIndyCore.rc
brcc32 RADStudio_XE3\dclIndyProtocols.rc
brcc32 RADStudio_XE4\IndySystem.rc
brcc32 RADStudio_XE4\IndyCore.rc
brcc32 RADStudio_XE4\IndyProtocols.rc
brcc32 RADStudio_XE4\dclIndyCore.rc
brcc32 RADStudio_XE4\dclIndyProtocols.rc
brcc32 RADStudio_XE5\IndySystem.rc
brcc32 RADStudio_XE5\IndyCore.rc
brcc32 RADStudio_XE5\IndyProtocols.rc
brcc32 RADStudio_XE5\dclIndyCore.rc
brcc32 RADStudio_XE5\dclIndyProtocols.rc
brcc32 RADStudio_XE6\IndySystem.rc
brcc32 RADStudio_XE6\IndyCore.rc
brcc32 RADStudio_XE6\IndyProtocols.rc
brcc32 RADStudio_XE6\dclIndyCore.rc
brcc32 RADStudio_XE6\dclIndyProtocols.rc
brcc32 RADStudio_XE7\IndySystem.rc
brcc32 RADStudio_XE7\IndyCore.rc
brcc32 RADStudio_XE7\IndyProtocols.rc
brcc32 RADStudio_XE7\dclIndyCore.rc
brcc32 RADStudio_XE7\dclIndyProtocols.rc
brcc32 RADStudio_XE8\IndySystem.rc
brcc32 RADStudio_XE8\IndyCore.rc
brcc32 RADStudio_XE8\IndyProtocols.rc
brcc32 RADStudio_XE8\dclIndyCore.rc
brcc32 RADStudio_XE8\dclIndyProtocols.rc
brcc32 RADStudio_10_0_Seattle\IndySystem.rc
brcc32 RADStudio_10_0_Seattle\IndyCore.rc
brcc32 RADStudio_10_0_Seattle\IndyProtocols.rc
brcc32 RADStudio_10_0_Seattle\dclIndyCore.rc
brcc32 RADStudio_10_0_Seattle\dclIndyProtocols.rc
brcc32 RADStudio_10_1_Berlin\IndySystem.rc
brcc32 RADStudio_10_1_Berlin\IndyCore.rc
brcc32 RADStudio_10_1_Berlin\IndyProtocols.rc
brcc32 RADStudio_10_1_Berlin\dclIndyCore.rc
brcc32 RADStudio_10_1_Berlin\dclIndyProtocols.rc
brcc32 RADStudio_10_2_Tokyo\IndySystem.rc
brcc32 RADStudio_10_2_Tokyo\IndyCore.rc
brcc32 RADStudio_10_2_Tokyo\IndyProtocols.rc
brcc32 RADStudio_10_2_Tokyo\dclIndyCore.rc
brcc32 RADStudio_10_2_Tokyo\dclIndyProtocols.rc
brcc32 ..\Source\IdAboutVCL.rc