@echo off
where resinator >nul 2>nul
if %errorlevel%==0 (set RC=resinator) else (set RC=rc)
%RC% "..\Source\Core\IdAboutVCL.rc"
%RC% "Delphi 4\IndySystem40.rc"
%RC% "Delphi 4\IndyCore40.rc"
%RC% "Delphi 4\dclIndyCore40.rc"
%RC% "Delphi 4\IndyProtocols40.rc"
%RC% "Delphi 4\dclIndyProtocols40.rc"
%RC% "Delphi 5\IndySystem50.rc"
%RC% "Delphi 5\IndyCore50.rc"
%RC% "Delphi 5\dclIndyCore50.rc"
%RC% "Delphi 5\IndyProtocols50.rc"
%RC% "Delphi 5\dclIndyProtocols50.rc"
%RC% "Delphi 6\IndySystem.rc"
%RC% "Delphi 6\IndyCore.rc"
%RC% "Delphi 6\dclIndyCore.rc"
%RC% "Delphi 6\IndyProtocols.rc"
%RC% "Delphi 6\dclIndyProtocols.rc"
%RC% "Delphi 7\IndySystem.rc"
%RC% "Delphi 7\IndyCore.rc"
%RC% "Delphi 7\dclIndyCore.rc"
%RC% "Delphi 7\IndyProtocols.rc"
%RC% "Delphi 7\dclIndyProtocols.rc"
%RC% "Delphi 8\IndySystem.rc"
%RC% "Delphi 8\IndyCore.rc"
%RC% "Delphi 8\dclIndyCore.rc"
%RC% "Delphi 8\IndyProtocols.rc"
%RC% "Delphi 8\dclIndyProtocols.rc"
%RC% "Delphi 2005\IndySystem.rc"
%RC% "Delphi 2005\IndyCore.rc"
%RC% "Delphi 2005\dclIndyCore.rc"
%RC% "Delphi 2005\IndyProtocols.rc"
%RC% "Delphi 2005\dclIndyProtocols.rc"
%RC% "RAD Studio 2006\IndySystem.rc"
%RC% "RAD Studio 2006\IndyCore.rc"
%RC% "RAD Studio 2006\dclIndyCore.rc"
%RC% "RAD Studio 2006\IndyProtocols.rc"
%RC% "RAD Studio 2006\dclIndyProtocols.rc"
%RC% "RAD Studio 2007\IndySystem.rc"
%RC% "RAD Studio 2007\IndyCore.rc"
%RC% "RAD Studio 2007\dclIndyCore.rc"
%RC% "RAD Studio 2007\IndyProtocols.rc"
%RC% "RAD Studio 2007\dclIndyProtocols.rc"
%RC% "RAD Studio 2009\IndySystem.rc"
%RC% "RAD Studio 2009\IndyCore.rc"
%RC% "RAD Studio 2009\dclIndyCore.rc"
%RC% "RAD Studio 2009\IndyProtocols.rc"
%RC% "RAD Studio 2009\dclIndyProtocols.rc"
%RC% "RAD Studio 2010\IndySystem.rc"
%RC% "RAD Studio 2010\IndyCore.rc"
%RC% "RAD Studio 2010\dclIndyCore.rc"
%RC% "RAD Studio 2010\IndyProtocols.rc"
%RC% "RAD Studio 2010\dclIndyProtocols.rc"
%RC% "RAD Studio XE\IndySystem.rc"
%RC% "RAD Studio XE\IndyCore.rc"
%RC% "RAD Studio XE\dclIndyCore.rc"
%RC% "RAD Studio XE\IndyProtocols.rc"
%RC% "RAD Studio XE\dclIndyProtocols.rc"
%RC% "RAD Studio XE2\IndySystem.rc"
%RC% "RAD Studio XE2\IndyCore.rc"
%RC% "RAD Studio XE2\dclIndyCore.rc"
%RC% "RAD Studio XE2\IndyProtocols.rc"
%RC% "RAD Studio XE2\dclIndyProtocols.rc"
%RC% "RAD Studio XE3\IndySystem.rc"
%RC% "RAD Studio XE3\IndyCore.rc"
%RC% "RAD Studio XE3\dclIndyCore.rc"
%RC% "RAD Studio XE3\IndyProtocols.rc"
%RC% "RAD Studio XE3\dclIndyProtocols.rc"
%RC% "RAD Studio XE4\IndySystem.rc"
%RC% "RAD Studio XE4\IndyCore.rc"
%RC% "RAD Studio XE4\dclIndyCore.rc"
%RC% "RAD Studio XE4\IndyProtocols.rc"
%RC% "RAD Studio XE4\dclIndyProtocols.rc"
%RC% "RAD Studio XE5\IndySystem.rc"
%RC% "RAD Studio XE5\IndyCore.rc"
%RC% "RAD Studio XE5\dclIndyCore.rc"
%RC% "RAD Studio XE5\IndyProtocols.rc"
%RC% "RAD Studio XE5\dclIndyProtocols.rc"
%RC% "RAD Studio XE6\IndySystem.rc"
%RC% "RAD Studio XE6\IndyCore.rc"
%RC% "RAD Studio XE6\dclIndyCore.rc"
%RC% "RAD Studio XE6\IndyProtocols.rc"
%RC% "RAD Studio XE6\dclIndyProtocols.rc"
%RC% "RAD Studio XE7\IndySystem.rc"
%RC% "RAD Studio XE7\IndyCore.rc"
%RC% "RAD Studio XE7\dclIndyCore.rc"
%RC% "RAD Studio XE7\IndyProtocols.rc"
%RC% "RAD Studio XE7\dclIndyProtocols.rc"
%RC% "RAD Studio XE8\IndySystem.rc"
%RC% "RAD Studio XE8\IndyCore.rc"
%RC% "RAD Studio XE8\dclIndyCore.rc"
%RC% "RAD Studio XE8\IndyProtocols.rc"
%RC% "RAD Studio XE8\dclIndyProtocols.rc"
%RC% "RAD Studio 10.0\IndySystem.rc"
%RC% "RAD Studio 10.0\IndyCore.rc"
%RC% "RAD Studio 10.0\dclIndyCore.rc"
%RC% "RAD Studio 10.0\IndyProtocols.rc"
%RC% "RAD Studio 10.0\dclIndyProtocols.rc"
%RC% "RAD Studio 10.1\IndySystem.rc"
%RC% "RAD Studio 10.1\IndyCore.rc"
%RC% "RAD Studio 10.1\dclIndyCore.rc"
%RC% "RAD Studio 10.1\IndyProtocols.rc"
%RC% "RAD Studio 10.1\dclIndyProtocols.rc"
%RC% "RAD Studio 10.2\IndySystem.rc"
%RC% "RAD Studio 10.2\IndyCore.rc"
%RC% "RAD Studio 10.2\dclIndyCore.rc"
%RC% "RAD Studio 10.2\IndyProtocols.rc"
%RC% "RAD Studio 10.2\dclIndyProtocols.rc"
%RC% "RAD Studio 10.3\IndySystem.rc"
%RC% "RAD Studio 10.3\IndyCore.rc"
%RC% "RAD Studio 10.3\dclIndyCore.rc"
%RC% "RAD Studio 10.3\IndyProtocols.rc"
%RC% "RAD Studio 10.3\dclIndyProtocols.rc"
%RC% "RAD Studio 10.4\IndySystem.rc"
%RC% "RAD Studio 10.4\IndyCore.rc"
%RC% "RAD Studio 10.4\dclIndyCore.rc"
%RC% "RAD Studio 10.4\IndyProtocols.rc"
%RC% "RAD Studio 10.4\dclIndyProtocols.rc"
%RC% "RAD Studio 11.0\IndySystem.rc"
%RC% "RAD Studio 11.0\IndyCore.rc"
%RC% "RAD Studio 11.0\dclIndyCore.rc"
%RC% "RAD Studio 11.0\IndyProtocols.rc"
%RC% "RAD Studio 11.0\dclIndyProtocols.rc"
%RC% "RAD Studio 12.0\IndySystem.rc"
%RC% "RAD Studio 12.0\IndyCore.rc"
%RC% "RAD Studio 12.0\dclIndyCore.rc"
%RC% "RAD Studio 12.0\IndyProtocols.rc"
%RC% "RAD Studio 12.0\dclIndyProtocols.rc"
%RC% "RAD Studio 13.0\IndySystem.rc"
%RC% "RAD Studio 13.0\IndyCore.rc"
%RC% "RAD Studio 13.0\dclIndyCore.rc"
%RC% "RAD Studio 13.0\IndyProtocols.rc"
%RC% "RAD Studio 13.0\dclIndyProtocols.rc"
