@echo off
call RADStudio_2009\Fullc_2009
call RADStudio_2010\Fullc_2010
call RADStudio_XE\Fullc_XE
call RADStudio_XE2\Fullc_XE2
call RADStudio_XE3\Fullc_XE3
call RADStudio_XE4\Fullc_XE4
call RADStudio_XE5\Fullc_XE5
call RADStudio_XE6\Fullc_XE6
call RADStudio_XE7\Fullc_XE7
call RADStudio_XE8\Fullc_XE8
call RADStudio_10.0_Seattle\Fullc_Seattle
call RADStudio_10.1_Berlin\Fullc_Berlin
call RADStudio_10.2_Tokyo\Fullc_Tokyo