  gsIdVersionMajor = 10;
  {$NODEFINE gsIdVersionMajor}
  gsIdVersionMinor = 6;
  {$NODEFINE gsIdVersionMinor}
  gsIdVersionRelease = 3;
  {$NODEFINE gsIdVersionRelease}
  gsIdVersionBuild = 8;
  {$NODEFINE gsIdVersionBuild}

  (*$HPPEMIT '#define gsIdVersionMajor 10'*)
  (*$HPPEMIT '#define gsIdVersionMinor 6'*)
  (*$HPPEMIT '#define gsIdVersionRelease 3'*)
  (*$HPPEMIT '#define gsIdVersionBuild 8'*)
  (*$HPPEMIT ''*)

  gsIdVersion = '10.6.3.8'; {do not localize}
  gsIdProductName = 'Indy';  {do not localize}
  gsIdProductVersion = '10.6.3'; {do not localize}
