  gsIdVersionMajor = 10;
  {$NODEFINE gsIdVersionMajor}
  gsIdVersionMinor = 6;
  {$NODEFINE gsIdVersionMinor}
  gsIdVersionRelease = 0;
  {$NODEFINE gsIdVersionRelease}
  gsIdVersionBuild = 0;
  {$NODEFINE gsIdVersionBuild}

  (*$HPPEMIT '#define gsIdVersionMajor 10'*)
  (*$HPPEMIT '#define gsIdVersionMinor 6'*)
  (*$HPPEMIT '#define gsIdVersionRelease 0'*)
  (*$HPPEMIT '#define gsIdVersionBuild 0'*)
  (*$HPPEMIT ''*)

  gsIdVersion = '10.6.0.0'; {do not localize}
  gsIdProductName = 'Indy';  {do not localize}
