  gsIdVersionMajor = 10;
  {$NODEFINE gsIdVersionMajor}
  gsIdVersionMinor = 5;
  {$NODEFINE gsIdVersionMinor}
  gsIdVersionRelease = 9;
  {$NODEFINE gsIdVersionRelease}
  gsIdVersionBuild = 0;
  {$NODEFINE gsIdVersionBuild}

  (*$HPPEMIT '#define gsIdVersionMajor 10'*)
  (*$HPPEMIT '#define gsIdVersionMinor 5'*)
  (*$HPPEMIT '#define gsIdVersionRelease 9'*)
  (*$HPPEMIT '#define gsIdVersionBuild 0'*)
  (*$HPPEMIT ''*)

  gsIdVersion = '10.5.9.0'; {do not localize}
  gsIdProductName = 'Indy';  {do not localize}
