[package]
name=indysystem
version=$(INDY_VERSION)
main=indy

[requires]
packages=fcl-base

[compiler]
options= -MDelphi $(OPT) -Scghi -CX -Ur -Xs -vew
unittargetdir= ../../units/$(CPU_TARGET)-$(OS_TARGET)
includedir=.
unitdir=.

[target]
units=indysystemfpc

[install]
fpcpackage=y
fpcsubdir=packages/extra
buildunit=indysystemfpc
