@echo off
call Fullc_4
call Fullc_5
call Fullc_6
call Fullc_2006
call Fullc_2007
call Fullc_2009
call Fullc_2010
call Fullc_XE
call Fullc_XE2
call Fullc_XE3
call Fullc_XE4
call Fullc_XE5
call Fullc_XE6
call Fullc_XE7
call Fullc_XE8
call Fullc_Seattle
call Fullc_Berlin
call Fullc_Tokyo