  gsIdVersionMajor = 11;
  {$NODEFINE gsIdVersionMajor}
  gsIdVersionMinor = 0;
  {$NODEFINE gsIdVersionMinor}
  gsIdVersionRelease = 0;
  {$NODEFINE gsIdVersionRelease}
  gsIdVersionBuild = 0;
  {$NODEFINE gsIdVersionBuild}

  (*$HPPEMIT '#define gsIdVersionMajor 11'*)
  (*$HPPEMIT '#define gsIdVersionMinor 0'*)
  (*$HPPEMIT '#define gsIdVersionRelease 0'*)
  (*$HPPEMIT '#define gsIdVersionBuild 0'*)
  (*$HPPEMIT ''*)

  gsIdVersion = '11.0.0.0'; {do not localize}
  gsIdProductName = 'Indy';  {do not localize}
  gsIdProductVersion = '11.0.0'; {do not localize}
