Document: indy-fpc
Title: Debian indy-fpc Manual
Author: <insert document author here>
Abstract: This manual describes what indy-fpc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/indy-fpc/indy-fpc.sgml.gz

Format: postscript
Files: /usr/share/doc/indy-fpc/indy-fpc.ps.gz

Format: text
Files: /usr/share/doc/indy-fpc/indy-fpc.text.gz

Format: HTML
Index: /usr/share/doc/indy-fpc/html/index.html
Files: /usr/share/doc/indy-fpc/html/*.html

  
