resinator "..\Lib\Source\Core\IdAboutVCL.rc"
resinator "Delphi 4\IndySystem40.rc"
resinator "Delphi 4\IndyCore40.rc"
resinator "Delphi 4\dclIndyCore40.rc"
resinator "Delphi 4\IndyProtocols40.rc"
resinator "Delphi 4\dclIndyProtocols40.rc"
resinator "Delphi 5\IndySystem50.rc"
resinator "Delphi 5\IndyCore50.rc"
resinator "Delphi 5\dclIndyCore50.rc"
resinator "Delphi 5\IndyProtocols50.rc"
resinator "Delphi 5\dclIndyProtocols50.rc"
resinator "Delphi 6\IndySystem.rc"
resinator "Delphi 6\IndyCore.rc"
resinator "Delphi 6\dclIndyCore.rc"
resinator "Delphi 6\IndyProtocols.rc"
resinator "Delphi 6\dclIndyProtocols.rc"
resinator "Delphi 7\IndySystem.rc"
resinator "Delphi 7\IndyCore.rc"
resinator "Delphi 7\dclIndyCore.rc"
resinator "Delphi 7\IndyProtocols.rc"
resinator "Delphi 7\dclIndyProtocols.rc"
resinator "Delphi 8\IndySystem.rc"
resinator "Delphi 8\IndyCore.rc"
resinator "Delphi 8\dclIndyCore.rc"
resinator "Delphi 8\IndyProtocols.rc"
resinator "Delphi 8\dclIndyProtocols.rc"
resinator "Delphi 2005\IndySystem.rc"
resinator "Delphi 2005\IndyCore.rc"
resinator "Delphi 2005\dclIndyCore.rc"
resinator "Delphi 2005\IndyProtocols.rc"
resinator "Delphi 2005\dclIndyProtocols.rc"
resinator "RAD Studio 2006\IndySystem.rc"
resinator "RAD Studio 2006\IndyCore.rc"
resinator "RAD Studio 2006\dclIndyCore.rc"
resinator "RAD Studio 2006\IndyProtocols.rc"
resinator "RAD Studio 2006\dclIndyProtocols.rc"
resinator "RAD Studio 2007\IndySystem.rc"
resinator "RAD Studio 2007\IndyCore.rc"
resinator "RAD Studio 2007\dclIndyCore.rc"
resinator "RAD Studio 2007\IndyProtocols.rc"
resinator "RAD Studio 2007\dclIndyProtocols.rc"
resinator "RAD Studio 2009\IndySystem.rc"
resinator "RAD Studio 2009\IndyCore.rc"
resinator "RAD Studio 2009\dclIndyCore.rc"
resinator "RAD Studio 2009\IndyProtocols.rc"
resinator "RAD Studio 2009\dclIndyProtocols.rc"
resinator "RAD Studio 2010\IndySystem.rc"
resinator "RAD Studio 2010\IndyCore.rc"
resinator "RAD Studio 2010\dclIndyCore.rc"
resinator "RAD Studio 2010\IndyProtocols.rc"
resinator "RAD Studio 2010\dclIndyProtocols.rc"
resinator "RAD Studio XE\IndySystem.rc"
resinator "RAD Studio XE\IndyCore.rc"
resinator "RAD Studio XE\dclIndyCore.rc"
resinator "RAD Studio XE\IndyProtocols.rc"
resinator "RAD Studio XE\dclIndyProtocols.rc"
resinator "RAD Studio XE2\IndySystem.rc"
resinator "RAD Studio XE2\IndyCore.rc"
resinator "RAD Studio XE2\dclIndyCore.rc"
resinator "RAD Studio XE2\IndyProtocols.rc"
resinator "RAD Studio XE2\dclIndyProtocols.rc"
resinator "RAD Studio XE3\IndySystem.rc"
resinator "RAD Studio XE3\IndyCore.rc"
resinator "RAD Studio XE3\dclIndyCore.rc"
resinator "RAD Studio XE3\IndyProtocols.rc"
resinator "RAD Studio XE3\dclIndyProtocols.rc"
resinator "RAD Studio XE4\IndySystem.rc"
resinator "RAD Studio XE4\IndyCore.rc"
resinator "RAD Studio XE4\dclIndyCore.rc"
resinator "RAD Studio XE4\IndyProtocols.rc"
resinator "RAD Studio XE4\dclIndyProtocols.rc"
resinator "RAD Studio XE5\IndySystem.rc"
resinator "RAD Studio XE5\IndyCore.rc"
resinator "RAD Studio XE5\dclIndyCore.rc"
resinator "RAD Studio XE5\IndyProtocols.rc"
resinator "RAD Studio XE5\dclIndyProtocols.rc"
resinator "RAD Studio XE6\IndySystem.rc"
resinator "RAD Studio XE6\IndyCore.rc"
resinator "RAD Studio XE6\dclIndyCore.rc"
resinator "RAD Studio XE6\IndyProtocols.rc"
resinator "RAD Studio XE6\dclIndyProtocols.rc"
resinator "RAD Studio XE7\IndySystem.rc"
resinator "RAD Studio XE7\IndyCore.rc"
resinator "RAD Studio XE7\dclIndyCore.rc"
resinator "RAD Studio XE7\IndyProtocols.rc"
resinator "RAD Studio XE7\dclIndyProtocols.rc"
resinator "RAD Studio XE8\IndySystem.rc"
resinator "RAD Studio XE8\IndyCore.rc"
resinator "RAD Studio XE8\dclIndyCore.rc"
resinator "RAD Studio XE8\IndyProtocols.rc"
resinator "RAD Studio XE8\dclIndyProtocols.rc"
resinator "RAD Studio 10.0\IndySystem.rc"
resinator "RAD Studio 10.0\IndyCore.rc"
resinator "RAD Studio 10.0\dclIndyCore.rc"
resinator "RAD Studio 10.0\IndyProtocols.rc"
resinator "RAD Studio 10.0\dclIndyProtocols.rc"
resinator "RAD Studio 10.1\IndySystem.rc"
resinator "RAD Studio 10.1\IndyCore.rc"
resinator "RAD Studio 10.1\dclIndyCore.rc"
resinator "RAD Studio 10.1\IndyProtocols.rc"
resinator "RAD Studio 10.1\dclIndyProtocols.rc"
resinator "RAD Studio 10.2\IndySystem.rc"
resinator "RAD Studio 10.2\IndyCore.rc"
resinator "RAD Studio 10.2\dclIndyCore.rc"
resinator "RAD Studio 10.2\IndyProtocols.rc"
resinator "RAD Studio 10.2\dclIndyProtocols.rc"
resinator "RAD Studio 10.3\IndySystem.rc"
resinator "RAD Studio 10.3\IndyCore.rc"
resinator "RAD Studio 10.3\dclIndyCore.rc"
resinator "RAD Studio 10.3\IndyProtocols.rc"
resinator "RAD Studio 10.3\dclIndyProtocols.rc"
resinator "RAD Studio 10.4\IndySystem.rc"
resinator "RAD Studio 10.4\IndyCore.rc"
resinator "RAD Studio 10.4\dclIndyCore.rc"
resinator "RAD Studio 10.4\IndyProtocols.rc"
resinator "RAD Studio 10.4\dclIndyProtocols.rc"
resinator "RAD Studio 11.0\IndySystem.rc"
resinator "RAD Studio 11.0\IndyCore.rc"
resinator "RAD Studio 11.0\dclIndyCore.rc"
resinator "RAD Studio 11.0\IndyProtocols.rc"
resinator "RAD Studio 11.0\dclIndyProtocols.rc"
resinator "RAD Studio 12.0\IndySystem.rc"
resinator "RAD Studio 12.0\IndyCore.rc"
resinator "RAD Studio 12.0\dclIndyCore.rc"
resinator "RAD Studio 12.0\IndyProtocols.rc"
resinator "RAD Studio 12.0\dclIndyProtocols.rc"
resinator "RAD Studio 13.0\IndySystem.rc"
resinator "RAD Studio 13.0\IndyCore.rc"
resinator "RAD Studio 13.0\dclIndyCore.rc"
resinator "RAD Studio 13.0\IndyProtocols.rc"
resinator "RAD Studio 13.0\dclIndyProtocols.rc"
